# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.15
_src_path: gh:rostools/template-workshop
author_family_name: Mazhari-Jensen
author_given_name: Daniel
github_board_number: '12'
github_repo: medicinsk-statistik
github_user: DanMazJen
workshop_type: general
