[files]
extend-exclude = [
  "*.json",
  "*.css",
  "*.svg",
  ".quarto/*",
  "_site/*",
  "_book/*",
  "_extensions/**",
  "_extensions/rostools/rostools-theme/_extensions/quarto-ext/fontawesome/assets/css/all.css",
  "*.bib",
  "arrows/*",
]

[default.extend-words]
# Map word typos to their corrections as: <typo> = "<correction>"
# When the correction is blank, the word is never valid. When the correction is the key, the word is always valid.
Ege = "Ege"
fpt = "fpt"
splitted = "splitted"
nd = "nd"
lage = "lage"
iz = "iz"
yhat = "yhat"
Stubbs = "Stubbs"
VAS = "VAS"

[default.extend-identifiers]
fpt = "fpt"
